server:
  port: 8002

spring:
  application:
    name: eureka-register-client-02
  profiles:
    active: dev

eureka:
  client:
    service-url:
      defaultZone: http://admin:Pssw0rd!qazAbcd!1234@eureka-server-register:8000/eureka/

    rest-template-timeout:
      connect-timeout: 5000
      connect-request-timeout: 8000
      socket-timeout: 10000


logging:
  level:
    root: debug
debug: true

